In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [15]:
## define vocabulary size
voc_size = 10000

In [16]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5439, 9179, 4560, 1349],
 [5439, 9179, 4560, 5659],
 [5439, 2102, 4560, 6939],
 [2932, 1106, 7883, 5108, 322],
 [2932, 1106, 7883, 5108, 6312],
 [2050, 5439, 9747, 4560, 3601],
 [1490, 3322, 4199, 5108]]

In [18]:
## word embedding represenation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [19]:
import numpy as np

In [22]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr, maxlen=sent_len, padding='pre')
print(embedded_docs)

[[   0    0    0    0 5439 9179 4560 1349]
 [   0    0    0    0 5439 9179 4560 5659]
 [   0    0    0    0 5439 2102 4560 6939]
 [   0    0    0 2932 1106 7883 5108  322]
 [   0    0    0 2932 1106 7883 5108 6312]
 [   0    0    0 2050 5439 9747 4560 3601]
 [   0    0    0    0 1490 3322 4199 5108]]


In [23]:
## feature representation
dim = 10

In [26]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_len))
model.compile('adam', 'mse')

c:\Deep Learning NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [32]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (8, 10)                │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 5439, 9179, 4560, 1349])

In [30]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[-0.03174862,  0.00579707,  0.02582811, -0.0410331 ,  0.0036191 ,
         0.0189888 , -0.03722296, -0.03321066,  0.01544641, -0.00346478],
       [-0.03174862,  0.00579707,  0.02582811, -0.0410331 ,  0.0036191 ,
         0.0189888 , -0.03722296, -0.03321066,  0.01544641, -0.00346478],
       [-0.03174862,  0.00579707,  0.02582811, -0.0410331 ,  0.0036191 ,
         0.0189888 , -0.03722296, -0.03321066,  0.01544641, -0.00346478],
       [-0.03174862,  0.00579707,  0.02582811, -0.0410331 ,  0.0036191 ,
         0.0189888 , -0.03722296, -0.03321066,  0.01544641, -0.00346478],
       [ 0.04830383, -0.04565966, -0.03862146,  0.04081473, -0.04009463,
        -0.03003958,  0.04266066,  0.04529833, -0.01884556,  0.00295655],
       [-0.00145762,  0.01974482,  0.01865565, -0.01638311, -0.02533774,
        -0.03401597,  0.04457617,  0.04510833, -0.02394227, -0.0448673 ],
       [-0.01885821, -0.02565966,  0.03972882,  0.03283146, -0.00698241,
         0.00180451,  0.02535423,  0.02845276